### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by LyoSU** [HookedBehemoth/ShareNX-Overlay#3]
I first came across modding under switch and saw your project, but it doesn’t suit me a bit and I wanted to change and rebuild it. But unfortunately I can’t do it. I get a build error. I found many instructions for building similar projects, but nothing helped.
Installed and configured devkitPro.

The last error I get:
```
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: gui_main.o] Ошибка 1
make: *** [Makefile:174: build] Ошибка 2
```

I would be very grateful for your help.

**Comment by HookedBehemoth** [comment]
Please paste the entire log

**Comment by LyoSU** [comment]
![image](https://user-images.githubusercontent.com/37080625/78414441-aa858a00-7624-11ea-9cfe-f8546220a27f.png)
Thanks for the quick response.
I also tried to build https://github.com/Reisyukaku/ReiNX and I had no problems with it. I believe that to build your project, install something extra.

**Comment by HookedBehemoth** [comment]
You are on an old libnx version. Please update to the latest release.

**Comment by LyoSU** [comment]
Unfortunately, this is not the case. I tried `pacman -Sy libnx` and it says to me that it is not outdated.

**Comment by HookedBehemoth** [comment]
Oh yeah... You need to use libnx master or wait for the next release.

**Comment by LyoSU** [comment]
Sad :( Thank you for your help. I will wait for the release.

**Comment by LyoSU** [comment]
Thank you very much again. I decided to compile the library from master. There were no problems with this. But for a long time I could not understand why I did not see the curl library. This is not mentioned anywhere, but it was necessary to install a switch-curl.

Everything worked out for me :)

**Comment by HookedBehemoth** [comment]
The new libnx version is up
