### ISSUE TITLE
How to upload to different sites and add new seperate features to allow more customization and to show how to allow what site to upload to.

### ISSUE THREAD

**Issue by Aliasim800** [HookedBehemoth/ShareNX-Overlay#7]
It looks like by default that the site the overlay uploads screenshots to is just lewd.pics just that site. I know about the ShareX .sxcu files but don't know where to put them, it needs to be more clear to where it is possible to add further customizations and where to put them, right now it's quite confusing for me and I don't understand, I've found the chosen config file from the ShareX repo but don't know how to make the overlay utilise it. This needs a bit of a fix and possibly in a future release more details on customization etc.

**Comment by HookedBehemoth** [comment]
not yet supported

**Comment by Aliasim800** [comment]
I hope by you saying "yet" means that this a thing to come in the future. I hope this gets implemented in a future release and soon, the last release was last year and i hope we are close to seeing a new one later in a month or 2.

**Comment by HookedBehemoth** [comment]
Merged the repos and it works but I broke the build recently.

https://github.com/hookedbehemoth/sharenx/tree/brls

**Comment by Aliasim800** [comment]
I don't understand what you mean by you "broke the build recently" but if I setup a configuration for the ShareNX hb app, the overlay also uses whatever site I put in the configuration?
